services:
  train:
    build:
      context: .
      dockerfile: Trainer.docker
    container_name: ollama-training
    volumes:
      - /Work/lumen/data/trainer/data:/workspace/data
      - /Work/lumen/data/trainer/outputs:/workspace/outputs
      - /Work/lumen/data/trainer/cache/huggingface:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    stdin_open: true
    tty: true

volumes:
  hf-cache:
